# 

Introduction to Numpy

1. N-Dimensional Array
2. Broadcasting
3. Mathematical Functions
4. Performance

NumPy Arrays

In [16]:
#Creating NumPy arrays
import numpy as np

#Create an array from a list
arr1=np.array([1,2,3,4,5])
print(f'Create an array from a list : \n {arr1}')

#Create an array of zeroes
arr2=np.zeros(5)
print(f'Create an array of zeroes : \n {arr2}')

#Create and array of ones
arr3=np.ones((3,3))
print(f'Create and array of ones : \n {arr3}')

#Create an array of evenly spaced values
arr4=np.arange(0,10,2)
print(f'Create an array of evenly spaced values : \n {arr4}')

#Create an array of random values
arr5=np.random.rand(3,3)
print(f'Create an array of random values : \n {arr5}')

Create an array from a list : 
 [1 2 3 4 5]
Create an array of zeroes : 
 [0. 0. 0. 0. 0.]
Create and array of ones : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Create an array of evenly spaced values : 
 [0 2 4 6 8]
Create an array of random values : 
 [[0.58242037 0.60378756 0.6531457 ]
 [0.63621875 0.10245368 0.55780171]
 [0.26376712 0.14941289 0.57668745]]


In [14]:
#Array Attributes : Shape, size, dtype

#Shape of the array
print(arr1.shape)

#Size of teh arrays
print(arr1.size)

#Data type of the array
print(arr1.dtype)

(5,)
5
int32


In [15]:
#Indexing and slicing arrays

#accessing elements
print(arr1[0])

#slicing
print(arr1[1:4])

1
[2 3 4]


In [18]:
#Array operations: Aritjmatic, aggregation, broadcasting

#Arithmatic operations
arr6=arr1+arr2
print(arr6)

#Aggregating Functions
print(np.sum(arr1))

#Broadcasting
arr7=arr1*2
print(arr7)

[1. 2. 3. 4. 5.]
15
[ 2  4  6  8 10]


Array Manipulation

In [25]:
#Reshaping Arrays

#Reshape array
arr8=np.arange(9).reshape(3,3)
print(arr8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
#Stacking and Splitting Arrays
#Stacking arrays vertically
arr9=np.vstack((arr8,arr8))
print(arr9)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
#Splitting Arrays
arr10,arr11=np.split(arr9,2)
print(arr10,arr11)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
#Transposing arrays
#transpose Array
arr12=arr8.T
print(arr12)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [29]:
#Universal functions (ufuncs)
#universal functions
arr13=np.sin(arr1)
print(arr13)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


Advanced NumPy

In [31]:
#Fancy Indexing
indices=np.array([0,2,4])
print(arr1[indices])

[1 3 5]


In [32]:
#Boolean Indexing
bool_arr=arr1 > 3
print(arr1[bool_arr])

[4 5]


In [34]:
#Vectorized operation
arr14=arr1+10
print(arr14)

[11 12 13 14 15]


In [35]:
#Broadcasting
arr15=arr1+np.array([[10],[20],[30],[40],[50]])
print(arr15)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
